### PR TITLE
Add resume section

### PR DESCRIPTION
**Pull request by GeneralFatPug**
Add resume section. This can be developed further later, but for the sake of getting our sections down I will add how it is so far. Plus we can see how we like the layout of it within the context of a full page

### CODE REVIEW

**Comment by jellyglitch** [comment]
Do you think you could centre it? For example, putting more space on left margin just because the right side looks more blank if you know what I mean.

**Comment by GeneralFatPug** [comment]
> Do you think you could centre it? For example, putting more space on left margin just because the right side looks more blank if you know what I mean.

sure, should be quick (so it will probably take long) I'll do that tonight after work

**Comment by GeneralFatPug** [comment]
I have centered the content within each grid cell. This is done by having each div have the class resume. I also showed how the backgrounds can be customized with different background colours

**Comment by GeneralFatPug** [comment]
Okay, one final check please. But it should be good to merge into main

**Comment by jellyglitch** [comment]
Looks goooood

**Pull request merged**
