### PR TITLE
Add footer with a centered Contact button

### PR DESCRIPTION
**Pull request by GeneralFatPug**
Add footer with centered contact button. No functionality yet

### CODE REVIEW

**Comment by GeneralFatPug** [comment]
I have added the requested logos and have done the positioning for them. You will just have to add what links you want them to lead to in the href of the <a>. I have added a comment above the lines needed

**Comment by jellyglitch** [comment]
Looks good, but can you also add the copyright jellypug heh.

**Comment by GeneralFatPug** [comment]
Roger Roger

**Comment by GeneralFatPug** [comment]
I have added the copyright in the footer. Like the one I showed you previously. But if you want it on the same line let me know and I will figure that out

**Comment by jellyglitch** [comment]
Actually that line is good but can you centre it instead? I think it would look good on that line centered.

**Comment by GeneralFatPug** [comment]
Okay, I have centered it and so I will merge to main

**Pull request merged**
